version: "3.4"
services:
  reproduction_db:
    image: mongo:4.4.10
    container_name: crowstream_reproduction_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${REPRODUCTION_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${REPRODUCTION_DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - reproduction_data:/data/db

  reproduction_ms:
    build:
      context: .
      dockerfile: Dockerfile
    image: crowstream_reproduction_ms
    container_name: crowstream_reproduction_ms
    env_file: .env
    depends_on:
      - reproduction_db
    ports:
      - "8080:8080"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: crowstream_mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${REPRODUCTION_DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${REPRODUCTION_DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${REPRODUCTION_DB_URL}
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    depends_on:
      - reproduction_db
    ports:
      - "8081:8081"

volumes:
  reproduction_data:
